version: '3'
services:
  db:
    image: mysql:8.0
    container_name: ddshare-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  web:
    build: .
    container_name: ddshare-web
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ddshare
    ports:
      - "3000:3000"
    depends_on:
      - db
